---
title: ''
---
Life is like a box of chocolates.

I was grown up in a small city in Guangdong, southern China. Tracing back to my childhood I'd had no idea about who and where I'm now. But beauty lies exactly in the uncertainty.

Now I'm already a senior undergraduate in applied math, visiting University of Wisconsin-Madison this fall. I spent most of my past years in China, with my warm family and friends. My parents are both engineers, which inspired me much in sciences. To read, study and discover the real truth of human kind, nature and even the outer space is fantastic, and I'm sure it's now my biggest dream to pursue in the lifetime.

I chose math. Nearly all the Chinese start to study math in our early childhood, which provides us a good chance in class for logical training. Firstly comparing the numbers, then calculating and solving the equations, further the beautiful proofs and theorems... everything is so charming in this system. When applied in other subjects, it's even more powerful, and usually requiring programming skills, so I learned to code after pacing into the university and found it with lots of fun. Coding can be a most useful helper when solving real problems, so it's very worth practicing it.

Now you may say I'm a mathematician, but life's far more beyond math. I love traveling, sports, music and any kind of arts. Traveling around the globe is definitely an exciting dream, and I've been to North America and Europe for now. Hugely different from east Asia, but it's really fun to explore different cultures. I get more tolerant and warm hearted after I started my way, and it's quite probably from the cultural shock. Don't judge before you know it, I think it's true in all aspects of life. Sports, music and arts - they're my favorites when I stay with myself, also very relaxing and inspiring. 

We live and think, but it's not the length of life dominating us but our hearts. So be brave!